// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOrgmKj7_93qvhUK8xRe0HPRU2GgTsVu0',
    appId: '1:469701590187:web:be5e74084322af8c1f0bee',
    messagingSenderId: '469701590187',
    projectId: 'flutter-jr-todo',
    authDomain: 'flutter-jr-todo.firebaseapp.com',
    storageBucket: 'flutter-jr-todo.firebasestorage.app',
    measurementId: 'G-L8YTNQ1QHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_TIOq5Olr8DXWt2VCbMocelU_iU49tp0',
    appId: '1:469701590187:android:614e0f81a40a52391f0bee',
    messagingSenderId: '469701590187',
    projectId: 'flutter-jr-todo',
    storageBucket: 'flutter-jr-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3wxeE26Y0ofzS1ehYuXCxM7UNr8gpyco',
    appId: '1:469701590187:ios:853910caf1d8b1331f0bee',
    messagingSenderId: '469701590187',
    projectId: 'flutter-jr-todo',
    storageBucket: 'flutter-jr-todo.firebasestorage.app',
    iosBundleId: 'com.example.flutterJrSample',
  );
}
